service: pierogis-bot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${env:MEAL_REQUESTS_BUCKET}
            - "/*"
    - Effect: 'Allow'
      Action:
        - 'states:SendTaskSuccess'
      Resource:
        Ref: MealChef
  deploymentBucket:
    name: ${env:MEAL_REQUESTS_BUCKET}
  environment:
    OAUTH_CONSUMER_KEY: ${env:OAUTH_CONSUMER_KEY}
    OAUTH_CONSUMER_SECRET: ${env:OAUTH_CONSUMER_SECRET}
    BEARER_TOKEN: ${env:BEARER_TOKEN}
    MEAL_REQUESTS_BUCKET: ${env:MEAL_REQUESTS_BUCKET}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  PollMentions:
    handler: handler.poll_mentions
    #    events:
    #      - schedule: rate(1 minute)
    environment:
      MEAL_CHEF_ARN:
        Ref: MealChef
      USER_ID: ${env:USER_ID}
  DownloadIngredients:
    handler: handler.download_ingredients
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DownloadIngredientsQueue
              - Arn
  CookDishes:
    handler: handler.cook_dishes
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CookDishesQueue
              - Arn
  ReplyTweets:
    handler: handler.reply_tweets
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ReplyTweetsQueue
              - Arn
    environment:
      OAUTH_ACCESS_TOKEN: ${env:OAUTH_ACCESS_TOKEN}
      OAUTH_ACCESS_TOKEN_SECRET: ${env:OAUTH_ACCESS_TOKEN_SECRET}

stepFunctions:
  stateMachines:
    MealChef:
      id: MealChef
      name: MealChef
      definition:
        Comment: "Workflow for cooking recipes from a batch request in parallel and executing a reply action"
        StartAt: CookMeal
        States:
          CookMeal:
            Type: Map
            MaxConcurrency: 0
            ItemsPath: $.dishes
            Iterator:
              StartAt: DownloadIngredients
              States:
                DownloadIngredients:
                  Type: Task
                  Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
                  Parameters:
                    QueueUrl:
                      Ref: DownloadIngredientsQueue
                    MessageBody:
                      mealId.$: $.mealId
                      urls.$: $.urls
                      taskToken.$: $$.Task.Token
                  ResultPath: $.keys
                  Next: CookDish
                CookDish:
                  Type: Task
                  Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
                  Parameters:
                    QueueUrl:
                      Ref: CookDishesQueue
                    MessageBody:
                      mealId.$: $.mealId
                      ingredients.$: $.ingredients
                      recipe.$: $.recipe
                      keys.$: $.keys
                      taskToken.$: $$.Task.Token
                  End: true
            Next: ReplyTweet
          ReplyTweet:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
            Parameters:
              QueueUrl:
                Ref: ReplyTweetsQueue
              MessageBody:
                keys: $.input
                mealId.$: $.mealId
                username.$: $.username
            End: true
  validate: true # enable pre-deployment definition validation (disabled by default

# you can add CloudFormation resource templates here
resources:
  Resources:
    DownloadIngredientsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: DownloadIngredientsQueue
    CookDishesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CookDishesQueue
    ReplyTweetsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ReplyTweetsQueue
  Outputs:
    MealChefArn:
      Description: "The ARN of the mealChef StateMachine"
      Value:
        Ref: MealChef

plugins:
  - serverless-python-requirements
  - serverless-step-functions

custom:
  pythonRequirements:
    dockerizePip: non-linux