service: pierogis-bot
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${file(./config.yml):${self:custom.stage}.ORDERS_BUCKET}
            - "/*"
    - Effect: 'Allow'
      Action:
        - 'states:SendTaskSuccess'
        - 'states:StartExecution'
      Resource:
        Ref: Kitchen
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:BatchWriteItem'
      Resource:
        Fn::GetAtt: [ OrdersTable, Arn ]
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameter'
        - 'ssm:PutParameter'
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:ssm:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":parameter"
            - "/pierogis/chef/sinceId"
  deploymentBucket:
    name: ${file(./config.yml):${self:custom.stage}.ORDERS_BUCKET}
  environment:
    OAUTH_CONSUMER_KEY: ${file(./config.yml):${self:custom.stage}.OAUTH_CONSUMER_KEY}
    OAUTH_CONSUMER_SECRET: ${file(./config.yml):${self:custom.stage}.OAUTH_CONSUMER_SECRET}
    BEARER_TOKEN: ${file(./config.yml):${self:custom.stage}.BEARER_TOKEN}
    ORDERS_BUCKET: ${file(./config.yml):${self:custom.stage}.ORDERS_BUCKET}

package:
  exclude:
    - 'events/**'
    - '.idea/**'
    - 'node_modules/**'
    - '.gitignore'
    - 'package.json'
    - 'package-lock.json'
    - 'README.md'
    - 'requirements.txt'
    - 'serverless.yml'
    - 'setup.py'

functions:
  pollMentions:
    handler: pierogis_bot.serverless.poll_mentions
    package:
      artifact:
    events:
      - schedule: ${self:custom.${self:custom.stage}.pollSchedule}
    environment:
      KITCHEN_ARN:
        Ref: Kitchen
      USER_ID: ${file(./config.yml):${self:custom.stage}.USER_ID}
      ORDERS_TABLE: ${self:custom.ordersTable}
  downloadIngredients:
    handler: pierogis_bot.serverless.download_ingredients
    package:
      artifact:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DownloadIngredientsQueue
              - Arn
  cookDish:
    handler: pierogis_bot.serverless.cook_dishes
    package:
      artifact:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CookDishQueue
              - Arn
  replyTweet:
    handler: pierogis_bot.serverless.reply_tweets
    package:
      artifact:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ServeOrderQueue
              - Arn
    environment:
      OAUTH_ACCESS_TOKEN: ${file(./config.yml):${self:custom.stage}.OAUTH_ACCESS_TOKEN}
      OAUTH_ACCESS_TOKEN_SECRET: ${file(./config.yml):${self:custom.stage}.OAUTH_ACCESS_TOKEN_SECRET}
      ORDERS_TABLE: ${self:custom.ordersTable}

stepFunctions:
  stateMachines:
    Kitchen:
      id: Kitchen
      name: ${self:custom.kitchenStateMachine}
      definition:
        Comment: "Workflow for cooking orders from a batch request in parallel and executing a reply action"
        StartAt: CookingOrder
        States:
          CookingOrder:
            Type: Map
            MaxConcurrency: 0
            ItemsPath: $.dishes
            Iterator:
              StartAt: DownloadingIngredients
              States:
                DownloadingIngredients:
                  Type: Task
                  Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
                  Parameters:
                    QueueUrl:
                      Ref: DownloadIngredientsQueue
                    MessageBody:
                      orderId.$: $.orderId
                      fileLinks.$: $.fileLinks
                      taskToken.$: $$.Task.Token
                  ResultPath: $.fileLinks
                  Next: CookingDish
                CookingDish:
                  Type: Task
                  Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
                  Parameters:
                    QueueUrl:
                      Ref: CookDishQueue
                    MessageBody:
                      orderId.$: $.orderId
                      ingredients.$: $.ingredients
                      recipes.$: $.recipes
                      seasoningLinks.$: $.seasoningLinks
                      fileLinks.$: $.fileLinks
                      taskToken.$: $$.Task.Token
                  End: true
            ResultPath: $.keys
            Next: OrderUp
          OrderUp:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage
            Parameters:
              QueueUrl:
                Ref: ServeOrderQueue
              MessageBody:
                keys.$: $.keys
                orderId.$: $.orderId
                replyType.$: $.replyType
            End: true
  validate: true # enable pre-deployment definition validation (disabled by default

# you can add CloudFormation resource templates here
resources:
  Resources:
    DownloadIngredientsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.downloadIngredientsQueue}
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [ DeadLetterQueue, Arn ]
          maxReceiveCount: 1
    CookDishQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.cookDishQueue}
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [ DeadLetterQueue, Arn ]
          maxReceiveCount: 1
    ServeOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.serveOrderQueue}
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [ DeadLetterQueue, Arn ]
          maxReceiveCount: 1
    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.deadLetterQueue}
        ReceiveMessageWaitTimeSeconds: 20
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ordersTable}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: replyType
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
          - AttributeName: replyType
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements
  - serverless-step-functions

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stage: ${opt:stage, self:provider.stage, dev}
  downloadIngredientsQueue: download-ingredients-${self:custom.stage}
  cookDishQueue: cook-dish-${self:custom.stage}
  serveOrderQueue: serve-order-${self:custom.stage}
  deadLetterQueue: dead-letter-${self:custom.stage}
  ordersTable: orders-${self:custom.stage}
  kitchenStateMachine: kitchen-${self:custom.stage}
  live:
    pollSchedule: rate(5 minutes)
  dev:
    pollSchedule:
