name: deploy live

on:
  push:
    tags:
      - v*

jobs:
  deploy-develop-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: serverless deploy
        shell: bash
        run: |
          serverless deploy --stage=live